name: build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - stable/**

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
      pull-requests: write
    steps:
      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@ee412cafe33e0d7d8b3bc7d0ca64c9f155e293c7 # main
        with:
          repository: openstack/placement
          ref: 42e8db0f9fa20e488ef3b726115dfa7466581c2a # stable/2024.2

      - uses: vexxhost/docker-atmosphere/.github/actions/build-image@ee412cafe33e0d7d8b3bc7d0ca64c9f155e293c7 # main
        with:
          image-name: placement
          build-contexts: placement=openstack/placement
          push: ${{ github.event_name != 'pull_request' }}
